### ISSUE TITLE
Sorting, Grouping & Filters

### ISSUE THREAD

**Issue by Xen0byte** [develerik/har-viewer#2]
###  Is your feature request related to a problem? Please describe.

It is currently not possible to sort, group or filter the calls based on specific criteria.

###  Describe the solution you'd like

- **Sorting**:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;by duration
- **Filtering**:&nbsp;&nbsp;&nbsp;&nbsp;by status code (1xx, 2xx, 3xx, 4xx, 5xx, 0?), by type (XHR, JS, HTML, CSS, WS, Font, Media, etc.)
- **Grouping**:&nbsp;&nbsp;by page

###  Describe alternatives you've considered

I've written my own HAR parser, but your one looks much nicer. I've also been using Google's one, but it can't be used offline.

###  Additional context

I develop test automation tools and, in some of them, I export HAR files for the test runs. I'm looking for something I could use to visualise the HARs as part of the test report.

**Comment by develerik** [comment]
That's a great idea, I've thought about it too. I will definitely take a look at it.

**Comment by develerik** [comment]
@Xen0byte I published a new version which includes a filter option for status code and resource type. This release also fixes a few bugs and updates the styling. What do you think about it?

**Comment by Xen0byte** [comment]
Hi @develerik, it's looking really good! Just the ability to filter by failed requests by itself is a massively helpful enhancement, or at least for my use case, but for others too, I'm certain. Apart from that, I'm not sure whether the type filter is fully implemented or not, but the only options I could see in the list were "All" and a blank option, so maybe something is not quite right there. I was running Firefox Developer Edition v87.0b3 (64-bit) when I noticed that.

**Comment by develerik** [comment]
Is it possible for you to send me a `.har` file which only shows "All" and the blank option? I tested the implementation with a file I got from recording `google.com` with this I was able to get all types contained in the file

**Comment by Xen0byte** [comment]
Yes, absolutely. I recorded it in a private session on a VPN by browsing reddit for a little bit, so I hope there's no sensitive data in there, but if you find anything please let me know: [www.reddit.com_Archive [21-03-01 18-34-40].har.zip](https://github.com/develerik/har-viewer/files/6063726/www.reddit.com_Archive.21-03-01.18-34-40.har.zip)

**Comment by develerik** [comment]
I don't know how sensitive the value is, but I found a jwt inside a cookie

**Comment by Xen0byte** [comment]
>  I don't know how sensitive the value is, but I found a jwt inside a cookie

Should be fine, I was in a brand new incognito session.

> Ah, I see. The information about the resource type is not included in the file.

Is the file content different from what you've been using for development? I've exported it from Firefox Developer Edition v87.0b3.

**Comment by develerik** [comment]
I've been using a file exported from google chrome which contains a `_resourceType` file for each entry. Like in this file
[test.txt](https://github.com/develerik/har-viewer/files/6064208/test.txt)

**Comment by develerik** [comment]
Sorry for the long wait. I have reworked my code and also implemented a new dialog that allows sorting, grouping and filtering. A few things are still missing, but I'd love to hear what you think about it.

**Comment by Xen0byte** [comment]
Hi @develerik, the new interface looks great. Please find below some feedback based on personal preferences and usage:

1. The new "Filter / Sort / Group" modal is a nice touch; I have some mixed feelings, however, in the sense that having the options on the main page saves a few clicks, which can add up if you need to filter/sort/group often, however having those options in modal form saves some screen real-estate so the results are nicer to look at. For usability purposes, I think it would be nice to have an option on the modal to attach it to the right side of the screen, for persistence, since, going through a few of my sample HARs, it would appear that that side of the viewport is not currently used that much (tested this on both my native 2560 x 1440 resolution and by emulating 1920 x 1080 via the devtools).

2. The main usability issue I'm seeing is that the filters should probably be multi-select elements; a nice-to-have would be the options that are not available to be greyed out. Additionally, for the status, it would be nice to be able to filter by range, rather than by specific status code; in my experience, this is a little more useful to someone that wants to have a look at all the errors, or all the redirects, etc.

3. Moreover, at the moment it seems to only be possible to filter by requests with an unknown status code by using 0 for the filter, which may not be entirely intuitive. That being said, I assume that unknown probably means anything outside of the known ranges, and maybe that will not always be equivalent to 0. Maybe using the actual unknown status code instead of "UNKNOWN" is slightly more scalable?

Overall, the project is looking great, and, in my opinion, is the best self-hostable HAR viewer out there. I would highly recommend you post about it on Hacker News and try to get more feedback from that forum of people.

Lastly, I am currently heading several automation projects that use Playwright, and one type of test artefact that the library generates is a HAR file of the entire test run. I'm currently not doing anything fancy with that but I plan to, and using any HAR viewer that is not self-hosted is a security risk, so your project is definitely something that I'm keeping a close eye on for when I will decide to generate nice visual reports of the test run network activity.

**Comment by develerik** [comment]
Thank you so much for your feedback, I really appreciate it.

The first two points are great ideas and I will definitely implement them.

Regarding the third point:
If the HAR provides a status code, it will be displayed (even if it is an unofficial one), 0 or unknown in this case means that the HAR does not provide any status code. This can happen, for example, if you use an adblocker and the request does not reach the server at all because it is blocked. Sometimes the HAR contains an error message in these cases (see screenshot), but not always.

![2021-07-10_12-48](https://user-images.githubusercontent.com/28714277/125160448-30c04280-e17d-11eb-91e4-b404b9d04ce8.png)

**Comment by Xen0byte** [comment]
Ah, fair enough, I just assumed that because if you filter by 0 you get some results, but if you filter by "unknown" or "UNKNOWN" you don't get any results.
